package swag.lab.test.log_in;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class AddTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void add() {
    driver.get("https://magento.softwaretestingboard.com/");
    driver.manage().window().setSize(new Dimension(1616, 876));
    driver.findElement(By.cssSelector(".button")).click();
    assertThat(driver.findElement(By.xpath("user-name")).getText(), is("What's New"));
  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
